"""add unique constraint to trade_history order_id

Revision ID: f1170c689736
Revises: e7f0b4fed770
Create Date: 2026-10-11 06:51:52.749787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1170c689736'
down_revision: Union[str, Sequence[str], None] = 'e7f0b4fed770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_trade_history_order_id', 'trade_history', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('uq_trade_history_order_id', 'trade_history', type_='unique')
    # ### end Alembic commands ###
